from typing import Dict, List
from app.ai_engine.core.model_manager import model_manager
import logging

logger = logging.getLogger(__name__)


class ExpenseCategorizer:
    def __init__(self, model_name: str = "meta-llama/Llama-3.2-3B-Instruct"):
        self.model_name = model_name
        self.tokenizer = model_manager.get_tokenizer(self.model_name)
        self.model = model_manager.get_model(self.model_name)
        self.pipeline = model_manager.get_pipeline()

        self.category_keywords = {
            "di chuyển": [
                "xe",
                "bus",
                "buýt",
                "taxi",
                "grab",
                "be",
                "gojek",
                "xăng",
                "gửi xe",
                "đổ xăng",
                "nhiên liệu",
                "dầu",
                "ga",
                "vé tàu",
                "vé máy bay",
                "vé xe",
                "vé tàu hỏa",
                "vé tàu thủy",
                "đi lại",
                "phí đỗ xe",
                "thuê xe",
                "bãi xe",
                "uber",
                "đi xe",
                "bến xe",
                "đi tàu",
                "đi máy bay",
                "taxi mai linh",
                "vinasun",
                "giao thông",
                "đi grabcar",
                "đi grabbike",
                "vé tàu điện",
                "metro",
                "đi chuyển",
                "đường sắt",
                "vé tàu cao tốc",
                "vietjet",
                "bamboo",
                "vietnam airline",
            ],
            "ăn uống": [
                "ăn",
                "đồ ăn",
                "cơm",
                "bún",
                "phở",
                "cafe",
                "cà phê",
                "cf",
                "trà sữa",
                "ăn sáng",
                "ăn trưa",
                "ăn tối",
                "nhà hàng",
                "quán ăn",
                "ăn vặt",
                "bữa ăn",
                "đồ uống",
                "nước uống",
                "bia",
                "rượu",
                "nước ngọt",
                "sinh tố",
                "nước ép",
                "bánh mì",
                "pizza",
                "sushi",
                "đồ nướng",
                "lẩu",
                "BBQ",
                "buffet",
                "đồ ăn nhanh",
                "fast food",
                "kfc",
                "mcdonald",
                "jollibee",
                "highlands",
                "starbucks",
                "cơm văn phòng",
                "cơm hộp",
                "món ăn",
                "đặt đồ",
                "delivery",
                "now",
                "shopeefood",
                "grabfood",
                "baemin",
                "gà rán",
                "thức ăn",
                "đồ nhậu",
                "quán nhậu",
                "quán cà phê",
                "đồ ăn vặt",
            ],
            "mua sắm": [
                "mua",
                "quần áo",
                "giày dép",
                "đồ dùng",
                "siêu thị",
                "chợ",
                "tạp hóa",
                "thời trang",
                "quần",
                "áo",
                "váy",
                "đầm",
                "giày",
                "dép",
                "túi xách",
                "ví",
                "đồng hồ",
                "trang sức",
                "nước hoa",
                "mỹ phẩm",
                "son",
                "phấn",
                "kem",
                "sữa rửa mặt",
                "dưỡng da",
                "mặt nạ",
                "trang điểm",
                "đồ điện tử",
                "đồ gia dụng",
                "nội thất",
                "đồ trang trí",
                "đồ chơi",
                "đồ cho bé",
                "tã",
                "sữa",
                "vinmart",
                "coopmart",
                "big c",
                "aeon",
                "lotte mart",
                "shopee",
                "lazada",
                "tiki",
                "sendo",
                "online",
                "đặt hàng",
                "uniqlo",
                "zara",
                "h&m",
                "shopping",
                "phụ kiện",
            ],
            "giải trí": [
                "xem phim",
                "du lịch",
                "chơi game",
                "karaoke",
                "sự kiện",
                "vé",
                "concert",
                "nhạc sống",
                "live show",
                "bar",
                "club",
                "hát",
                "tiệc",
                "rạp phim",
                "cgv",
                "lotte cinema",
                "galaxy cinema",
                "netflix",
                "spotify",
                "kênh truyện",
                "truyện tranh",
                "sách truyện",
                "trò chơi",
                "game online",
                "steam",
                "garena",
                "pubg",
                "liên quân",
                "fifa",
                "ps4",
                "ps5",
                "xbox",
                "nintendo",
                "picnic",
                "dã ngoại",
                "công viên",
                "khu vui chơi",
                "khu du lịch",
                "giải trí",
                "festival",
                "lễ hội",
                "show",
                "biểu diễn",
                "youtube premium",
                "spotify premium",
                "apple music",
                "môn thể thao",
                "sân vận động",
                "xem bóng đá",
            ],
            "hóa đơn": [
                "điện",
                "nước",
                "internet",
                "điện thoại",
                "tiền nhà",
                "phí dịch vụ",
                "chung cư",
                "hóa đơn",
                "bill",
                "cáp",
                "truyền hình",
                "thuê nhà",
                "thuê phòng",
                "tiền thuê",
                "phí quản lý",
                "phí gửi xe",
                "phí chung cư",
                "phí an ninh",
                "phí vệ sinh",
                "tiền điện",
                "tiền nước",
                "tiền mạng",
                "tiền wifi",
                "tiền cáp",
                "tiền gas",
                "gas",
                "thuế",
                "bảo hiểm",
                "phí ngân hàng",
                "phí thẻ",
                "phí duy trì",
                "phí dịch vụ",
                "tiền điện thoại",
                "cước điện thoại",
                "cước di động",
                "viettel",
                "vinaphone",
                "mobifone",
                "fpt",
                "vnpt",
                "cmc",
                "vinhomes",
                "tiền trọ",
                "tiền thuê nhà",
                "cước internet",
            ],
            "sức khỏe": [
                "thuốc",
                "khám bệnh",
                "bệnh viện",
                "gym",
                "thể thao",
                "phòng tập",
                "yoga",
                "chạy bộ",
                "boxing",
                "pilates",
                "fitness",
                "đồ thể thao",
                "vitamin",
                "thực phẩm chức năng",
                "khám sức khỏe",
                "nha khoa",
                "nha sĩ",
                "đau răng",
                "răng miệng",
                "mắt kính",
                "kính",
                "khám mắt",
                "khám thai",
                "thai sản",
                "y tế",
                "bảo hiểm y tế",
                "phí khám",
                "viện phí",
                "mua thuốc",
                "nhà thuốc",
                "pharmacity",
                "long châu",
                "an khang",
                "dược phẩm",
                "vật tư y tế",
                "thiết bị y tế",
                "mát xa",
                "spa",
                "chăm sóc sức khỏe",
                "thiền",
                "châm cứu",
                "vật lý trị liệu",
                "khẩu trang",
                "xét nghiệm",
                "test covid",
                "xông hơi",
                "thực phẩm bổ sung",
            ],
            "giáo dục": [
                "học phí",
                "sách",
                "khóa học",
                "đào tạo",
                "lớp học",
                "học",
                "giáo trình",
                "tài liệu",
                "bút",
                "vở",
                "đồ dùng học tập",
                "văn phòng phẩm",
                "laptop",
                "máy tính",
                "thiết bị học tập",
                "thiết bị điện tử",
                "khóa học online",
                "e-learning",
                "udemy",
                "coursera",
                "học tiếng anh",
                "luyện thi",
                "gia sư",
                "tiền học",
                "trường học",
                "đại học",
                "cao đẳng",
                "cấp 3",
                "phổ thông",
                "mẫu giáo",
                "nhà trẻ",
                "giáo viên",
                "dạy học",
                "dạy kèm",
                "phần mềm học tập",
                "từ điển",
                "sách giáo khoa",
                "sách tham khảo",
                "đồng phục",
                "trại hè",
                "chứng chỉ",
                "bằng cấp",
                "toeic",
                "ielts",
                "toefl",
                "học thêm",
            ],
            "công việc": [
                "văn phòng phẩm",
                "in ấn",
                "photocopy",
                "công cụ",
                "phần mềm",
                "đồng nghiệp",
                "khách hàng",
                "đối tác",
                "tiếp khách",
                "công tác",
                "đi công tác",
                "dự án",
                "hội thảo",
                "workshop",
                "seminar",
                "đào tạo công việc",
                "phí thành viên",
                "hội viên",
                "hiệp hội",
                "networking",
                "tuyển dụng",
                "quảng cáo",
                "marketing",
                "vật phẩm văn phòng",
                "giấy in",
                "mực in",
                "thiết bị văn phòng",
                "đầu tư công việc",
                "phần mềm chuyên dụng",
                "dịch vụ chuyên môn",
                "tư vấn công việc",
                "công tác phí",
            ],
            "khác": [],
        }

    def _classify_with_llm(self, description: str) -> str:
        try:
            messages = [
                {
                    "role": "system",
                    "content": "Bạn là một AI phân loại chi tiêu. Bạn CHỈ trả về tên danh mục, không có bất kỳ văn bản nào khác.",
                },
                {
                    "role": "user",
                    "content": f"Phân loại chi tiêu sau vào một trong các danh mục sau: {', '.join(self.category_keywords.keys())}. Mô tả: {description}. Danh mục:",
                },
            ]

            outputs = self.pipeline(
                messages,
                max_new_tokens=20,
                do_sample=False,
                pad_token_id=self.tokenizer.eos_token_id,
            )
            category = outputs[0]["generated_text"].strip().lower()

            valid_categories = self.category_keywords.keys()
            if category in valid_categories:
                return category
            else:
                return "khác"

        except Exception as e:
            logger.exception(f"Error classifying with LLM: {e}")  # Log full traceback
            return "khác"

    def predict_category(self, description: str) -> str:
        if not description:
            return "khác"

        description = description.lower()
        best_category = "khác"
        max_matches = 0
        scores = {}

        for category, keywords in self.category_keywords.items():
            matches = sum(1 for keyword in keywords if keyword in description)
            scores[category] = matches

        # Find category with highest score
        best_category = max(scores, key=scores.get)
        max_matches = scores[best_category]

        if max_matches >= 1:  # Use the best category if good match
            return best_category
        else:  # Use LLM
            return self._classify_with_llm(description)

    def update_keywords(self, new_keywords: Dict[str, List[str]]):
        for category, keywords in new_keywords.items():
            if category in self.category_keywords:
                self.category_keywords[category].extend(keywords)
            else:
                self.category_keywords[category] = keywords
